### ISSUE TITLE
Could u provide the PPI.yaml,Reddit.yaml, Amazon-670K.yaml and Amazon-3K?

### ISSUE THREAD

**Issue by sunfeng90** [VITA-Group/L2-GCN#2]
Hi, thanks for your great project and paper.

I found cora.yaml and pubmed.yaml in the project. Could u provide the left datasets yaml ?

Thank you.

**Comment by yyou1996** [comment]
Hi @sunfeng90,

Sure. I will upload them within this or next week.

**Comment by sunfeng90** [comment]
> Hi @sunfeng90,
> 
> Sure. I will upload them within this or next week.

Okay, thanks.

**Comment by sunfeng90** [comment]
> Hi @sunfeng90,
> 
> Sure. I will upload them within this or next week.

If u have any time, please upload them. I'm doing experiment on your code and L-GCN.  Thanks a lot.

**Comment by yyou1996** [comment]
Hi @sunfeng90,

Sorry for the late reply, The needed files are uploaded, and any question just let me know. Happy Thanksgiving!

**Comment by sunfeng90** [comment]
Okay, thanks a lot.
